Fix bug that could pass max_position_embeddings=None
This would be the case when loading a model from_pretrained() that
had been saved with "freq_max_position_embeddings" = None, leading to
TypeError: arange requires ndarray or scalar arguments, got <class 'NoneType'> at position 0.